Resources:
  DnsRecord:
    Type: "AWS::Route53::RecordSet"
    DependsOn:
      - WebsiteBucket
      - WebsiteBucketPolicy
      - CFDistribution
    Properties:
      Comment: "Alias CloudFront for ${custom.domain.subdomain}"
      HostedZoneId: ${custom.domain.id}
      Type: CNAME
      TTL: "300"
      Name: ${custom.domain.subdomain}
      ResourceRecords:
        - "#{CFDistribution.DomainName}"
