service: wallbox
app: wallbox
org: fedeiglesias
name: wallbox

provider:
  name: aws
  runtime: nodejs10.x

component: website

inputs:
  domain: wallbox.pixium.io
  src:
    src: ./src
    hook: npm run build
    dist: ./dist