service: wallbox
app: wallbox
org: fedeiglesias
name: wallbox
stage: prod

provider:
  name: aws

component: website

inputs:
  domain: wallbox.pixium.io
  src:
    src: ./src
    hook: npm run build
    dist: ./dist